import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const openSauseSans = localFont({
  src: [
    {
      path: "../assets/fonts/OpenSauceSans-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/OpenSauceSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/OpenSauceSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/OpenSauceSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

const Bebas = localFont({
  src: [
    {
      path: "../assets/fonts/BebasNeue-Regular.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSauseSans.className} ${Bebas.variable} dark`}>
        {children}
      </body>
    </html>
  );
}
